// =====================================================
// GAME VARIABLES
// =====================================================

export const variable = {
    room: null,
    player: null,
    playerId: null,
    username: null,
    allPlayers: {},
    cursors: null,
    wasd: null,
    groundBlocks: [],
    stoneBlocks: [],
    spikeBlocks: [],
    platforms: [],
    enemySpawnTimer: 0,
    checkpoints: [],
    lastCheckpoint: null,
    playerHealth: 0,
    healthBarBg: null,
    healthBarFill: null,
    healthBarDelayed: null,
    healthBarTargetWidth: 300,
    playerSpawnProtected: false,
    sightGraphics: null,
    grassScale: null,
    grassScaledWidth: null,
    grassScaledHeight: null,
    stoneScale: null,
    stoneW: null,
    stoneH: null,
    blockWidth: null,
    blockHeight: null,
    deathPixels: [],
    deathScreen: null,
    sceneRef: null,
    enemies: {},
    enemyVisuals: [],
    xpHud: null,
    playerMaxHealth: 100,
    spawnExited: false,
    persistentXP: 0,
    runXP: 0,
    allBlocks: [],
}